vich_uploader:
    db_driver: orm
    
    #metadata spécifie que la configuration se fera via les attributs PHP
    metadata:
        type: attribute
    
    mappings:
        #nom de notre mapping
        poster_file:
            uri_prefix: /uploads/images/posters
            #upload_directory défini  dans services.yaml
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        photo_file:
            uri_prefix: /uploads/images/actorPhoto
            #upload_directory défini  dans services.yaml
            upload_destination: '%upload_photo%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
